### ISSUE TITLE
[webpack-cli] ReferenceError: path is not defined

### ISSUE THREAD

**Issue by robdekort** [marceickhoff/laravel-mix-modernizr#8]
Hi there! I enjoy using your package. Thanks a lot for that. However since upgrading to Laravel Mix 6 I can't get it to compile anymore. `npm run dev` greets me with:

```
[webpack-cli] ReferenceError: path is not defined
    at /Users/robdekort/Sites/statamic-peak/node_modules/laravel-mix-modernizr/index.js:49:17
    at Array.forEach (<anonymous>)
    at Modernizr.register (/Users/robdekort/Sites/statamic-peak/node_modules/laravel-mix-modernizr/index.js:34:28)
    at Object.components.<computed> [as modernizr] (/Users/robdekort/Sites/statamic-peak/node_modules/laravel-mix/src/components/ComponentRegistrar.js:118:53)
    at Object.<anonymous> (/Users/robdekort/Sites/statamic-peak/webpack.mix.js:9:6)
    at Module._compile (/Users/robdekort/Sites/statamic-peak/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19)
npm ERR! code 2
npm ERR! path /Users/robdekort/Sites/statamic-peak
npm ERR! command failed
npm ERR! command sh -c webpack --progress '--config=/Users/robdekort/Sites/statamic-peak/node_modules/laravel-mix/setup/webpack.config.js'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/robdekort/.npm/_logs/2020-12-28T12_27_03_144Z-debug.log
npm ERR! code 2
npm ERR! path /Users/robdekort/Sites/statamic-peak
npm ERR! command failed
npm ERR! command sh -c mix

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/robdekort/.npm/_logs/2020-12-28T12_27_03_176Z-debug.log
```

The build does compile without using `laravel-mix-modernizr`. I get the feeling this package might need to be made compatible with Laravel Mix 6. Do you maybe have any thoughts on this?

**Comment by marceickhoff** [comment]
Hi! Thank you for your opening this issue. This has been resolved with aa681bf3b41194f90328f78379611cb09754bf2a by adding the explicit `require` of the `path` package.
